#!/bin/bash
response=n
while true;
do
	echo -n  "provide the username: "
        read newusers
        useradd $newusers
        echo " "
        echo "user $newusers has been created with sudo power"
        echo "$newusers        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers.d/mysudoers
        echo " "
        #echo "Here are your sudo users"
        # cat /etc/sudoers.d/mysudoers
	echo -n "more user(y/n): "
	read response
	if [[ $response == "n" ]];
	then
		break

	fi
done
echo " "
echo " Here is the list of your sudo users"
echo " "
cat /etc/sudoers.d/mysudoers
